"""loanr5

Revision ID: dbd3225145ea
Revises: 290c527d30c2
Create Date: 2025-12-03 21:37:41.878752

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dbd3225145ea'
down_revision: Union[str, Sequence[str], None] = '290c527d30c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('loans', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    # ### end Alembic commands ###
